### ISSUE TITLE
Private repository?

### ISSUE THREAD

**Issue by RDIL** [tbhaxor/morphine#1]
I can’t see the repo in desktop version but I can in mobile version whattttt

**Comment by tbhaxor** [comment]
If you are able to create issue can see w/o logging in then its publicly visible :smile:

**Comment by tbhaxor** [comment]
@RDIL if your issue is solved, please close this issue

Thanku

**Comment by RDIL** [comment]
But on both my phone and laptop it still says “GitHub.com/tbhaxor/morphine
is not allowed at this time”

**Comment by tbhaxor** [comment]
Can you show me the screen shot?

**Comment by RDIL** [comment]
Sure one moment

**Comment by tbhaxor** [comment]
hey @RDIL  i am closing this issue since i didnt  hear from your side for so long. Anytime you encounter same issue you can reopen it

Thnx
